services:
  hc_mdw:
    # image: aeternity/ae_mdw
    # platform: linux/x86_64
    image: aeternity/ae_mdw:local
    build:
      context: https://github.com/aeternity/ae_mdw.git#master
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
        # NODE_VERSION: master
        NODE_IMAGE: aeternity/aeternity:master
    hostname: hc_mdw
    networks:
      default:
        aliases:
          - "hc-mdw.local.gd"
    ports:
      - "24000:24000" #MDW's port
      - "24001:24001" #MDW's websocket port
      - "23113:23113" #Node's internal API port
      - "23013:23013" #Node's external API port
      - "23014:23014" #Node's channels websocket port
      - "23015:23015" #Node's sync port
    volumes:
      - ${PWD}/node/hyperchain/aeternity.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/hyperchain/accounts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.ceres/hc_devnet_accounts.json
      - ${PWD}/node/hyperchain/contracts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.ceres/hc_devnet_contracts.json
      - ${PWD}/node/hyperchain/keys:/home/aeternity/node/local/rel/aeternity/data/aecore/keys
      - ae_hyperchain_node_db:/home/aeternity/node/local/rel/aeternity/data/mnesia
      - ae_hyperchain_mdw_db:/home/aeternity/node/local/rel/aeternity/data/mdw.db
    environment:
      # mdw configuration
      ENABLE_TELEMETRY: "false"
      ENABLE_CONSOLE_LOG: "true"
      LOG_LEVEL: warning
      PORT: 24000
      WS_PORT: 24001
      # node configuration
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
      AE__HTTP__EXTERNAL__PORT: 23013
      AE__HTTP__INTERNAL__PORT: 23113
      AE__WEBSOCKET__CHANNEL__PORT: 23014
      AE__SYNC__PORT: 23015
      AE__HTTP__CORS__ALLOW_DOMAINS: '["*"]'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:24000/status"]
        start_period: 20s
        interval: 3s
        timeout: 10s
        retries: 5
    depends_on:
      mdw:
        condition: service_healthy

  hc_faucet:
    platform: linux/x86_64
    image: aeternity/aepp-faucet-nodejs
    environment:
      NODE_URL: http://hc_mdw:23013/
      EXPLORER_URL: http://localhost:28020
      FAUCET_ACCOUNT_PRIV_KEY: EBEAB332C627DC6F79E1D305ABFD448781C0101F3E1A5261B37EC4821702E4032757508127D7A9BA0AC449547085FAF3A18C96903800C0245F0A79949D930792
    ports:
     - "28030:5000"
    depends_on:
      hc_mdw:
        condition: service_healthy

  hc_explorer:
    image: aeternity/mdw-frontend
    ports:
     - "28020:3000"
    environment:
      NUXT_APP_NODE_URL: http://hc-mdw.local.gd:23013/v3
      NUXT_APP_MDW_URL: http://hc-mdw.local.gd:24000
      NUXT_APP_NODE_WS: ws://localhost:24001/websocket

      NUXT_APP_OTHER_DEPLOYMENTS: ""
      NUXT_APP_NETWORK_NAME: HYPERCHAIN LOCAL
      NUXT_APP_ENABLE_FAUCET: ""
      NUXT_APP_FAUCET_API: http://localhost:28030/account
    depends_on:
      hc_mdw:
        condition: service_healthy

  hc_base_backend:
    image: aeternity/aepp-base-backend
    environment:
      VAPID_SUBJECT: 'mailto: <info@aeternity.com>'
      VAPID_PUBLIC_KEY: 'BKdMuWCMzVPLTY-ClCNBanQ5Thgji_VMOQKsmTGlTs5DqVyXU4aFv2eHUs2YwK3XY-RS9HdjkIRJK3E20n251Rw'
      VAPID_PRIVATE_KEY: 'LzjNvVH109jxcAGDMe59zLM-gNaeo9QypJl82Thtmts'
    ports:
     - "28011:8079"

  hc_base:
    image: aeternitybot/aepp-base:develop
    platform: linux/x86_64
    environment:
      VUE_APP_NETWORK_NAME: Hyperchain Local
      VUE_APP_NODE_URL: http://localhost:23013
      VUE_APP_MIDDLEWARE_URL: http://localhost:24000
      VUE_APP_EXPLORER_URL: http://localhost:28020
      VUE_APP_COMPILER_URL: http://localhost:8040
      VUE_APP_BACKEND_URL: http://localhost:28011
    ports:
     - "28010:80"
    depends_on:
      hc_base_backend:
        condition: service_started
      hc_mdw:
        condition: service_healthy

  ui:
    platform: linux/x86_64
    image: public.ecr.aws/aeternity/aepp-hyperchain:v0.8
    environment:
      AE_FAUCET_URL: "http://localhost:28030/"
      AE_WALLET_URL: "http://localhost:28010/"
      AE_NODE_URL: "http://hc-mdw.local.gd:23013/"
      STAKING_CONTRACT: "ct_LRbi65kmLtE7YMkG6mvG5TxAXTsPJDZjAtsPuaXtRyPA7gnfJ"
      HC_ELECTION_CONTRACT: "ct_t7ESuRFvGdYHwM6KJhKbSnFUJQhnB9aCFed1RWR89ShNDgwWA"
    ports:
     - "28040:3000"
    depends_on:
      hc_mdw:
        condition: service_healthy

  hc_static:
    image: nginx:1.13.8
    ports:
        - 8080:80
    volumes:
        - ${PWD}/nginx/html/hyperchain:/usr/share/nginx/html
    healthcheck:
        test: ["CMD", "service", "nginx", "status"]
        start_period: 3s
        interval: 3s
        timeout: 1s
        retries: 5
    depends_on:
      mdw:
        condition: service_healthy
      base:
        condition: service_started
      faucet:
        condition: service_started
      explorer:
        condition: service_started

  hc_instructions:
    image: alpine
    command: echo "!!!OPEN http://localhost:8080 FOR MORE INFROMATION ABOUT HYPERCHAIN!!!"
    depends_on:
      static:
        condition: service_healthy

volumes:
  ae_hyperchain_node_db:
  ae_hyperchain_mdw_db:
