version: '3'
services:
  node1:
    image: aeternity/aeternity:${IMAGE_TAG:-latest}
    hostname: node1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/node1_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
      - ${PWD}/node/accounts.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
      - ae_node1_db:/home/aeternity/node/data/mnesia
    ports:
     - "3013:3013"
     - "3113:3113"
     - "3014:3014"

  nginx:
    image: nginx:1.13.8
    # In case a debug logging is needed
    # command: [nginx-debug, '-g', 'daemon off;']
    hostname: nginx
    ports:
     - "8080:8080"
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx/cors.conf:/etc/nginx/cors.conf
      - ${PWD}/nginx/ws.conf:/etc/nginx/ws.conf

volumes:
  ae_node1_db:
