services:
  # Mining is supported only on linux/x86_64 and mdw doesn't run in emulation, thus an extra node to mine
  node:
    platform: linux/x86_64
    image: aeternity/aeternity:v7.3.0-rc1
    hostname: node1
    ports:
      - "13013:3013" #Node's default external API port
    volumes:
      - ${PWD}/node/config/node1_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/config/accounts.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
      - ae_node_db:/home/aeternity/node/data/mnesia
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
      AE__HTTP__CORS__ALLOW_DOMAINS: '["*"]'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3013/v3/status"]
        start_period: 20s
        interval: 3s
        timeout: 10s
        retries: 5

  mdw:
    image: aeternity/ae_mdw:1.97.0
    # platform: linux/x86_64
    # image: aeternity/ae_mdw:local
    # build:
    #   context: https://github.com/aeternity/ae_mdw.git#v1.97.0
    #   args:
    #     BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    #     NODE_VERSION: 7.2.0
    hostname: mdw
    networks:
      default:
        aliases:
          - "mdw.local.gd"
    ports:
      - "4000:4000" #MDW's default port
      - "4001:4001" #MDW's websocket default port
      - "3113:3113" #Node's default internal API port
      - "3013:3013" #Node's default external API port
      - "3014:3014" #Node's channels default websocket port
    volumes:
      - ${PWD}/node/config/node2_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/config/accounts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.genesis/accounts_test.json
      - ${PWD}/node/keys/node2:/home/aeternity/node/local/rel/aeternity/keys
      - ae_mdw_node_db:/home/aeternity/node/local/rel/aeternity/data/mnesia
      - ae_mdw_db:/home/aeternity/node/local/rel/aeternity/data/mdw.db
    environment:
      # mdw configuration
      ENABLE_TELEMETRY: "false"
      ENABLE_CONSOLE_LOG: "true"
      LOG_LEVEL: warning
      # node configuration
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
      AE__MINING__AUTOSTART: "false"
      AE__HTTP__CORS__ALLOW_DOMAINS: '["*"]'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4000/status"]
        start_period: 20s
        interval: 3s
        timeout: 10s
        retries: 5
    depends_on:
      node:
        condition: service_healthy

  faucet:
    image: aeternity/aepp-faucet-nodejs:v1.2.1
    platform: linux/x86_64
    environment:
      NODE_URL: http://mdw:3013/
      EXPLORER_URL: http://localhost:8020
      FAUCET_ACCOUNT_PRIV_KEY: EE796C442F410F8B1AACFA877A3FE734BC79CE90C8272570AC1DD8CDAC38F104D9CA6CADC0630D0A817C4756E87994B1F3FEA058AECC16720F2A33474B138710
      SPEND_TX_TTL: 10
    ports:
     - "8030:5000"
    depends_on:
      mdw:
        condition: service_healthy

  aescan:
    image: aeternity/aescan:pr-1035
    platform: linux/x86_64
    ports:
      - "8020:80"
    environment:
      NUXT_PUBLIC_NODE_URL: http://mdw.local.gd:3013
      NUXT_PUBLIC_MIDDLEWARE_URL: http://mdw.local.gd:4000
      NUXT_PUBLIC_WEBSOCKET_URL: ws://mdw.local.gd:4001/v3/websocket
      NUXT_PUBLIC_NETWORK_ID: devnet
      NUXT_PUBLIC_NETWORK_NAME: LOCALNET
      NUXT_PUBLIC_APP_DOMAIN: http://localhost:8020
      NUXT_PUBLIC_DEBUG_MODE: false
    depends_on:
      mdw:
        condition: service_healthy

  compiler:
    image: aeternity/aesophia_http:v6.1.0
    ports:
      - "8040:3080"

  base_backend:
    image: aeternity/aepp-base-backend
    environment:
      VAPID_SUBJECT: 'mailto: <info@aeternity.com>'
      VAPID_PUBLIC_KEY: 'BKdMuWCMzVPLTY-ClCNBanQ5Thgji_VMOQKsmTGlTs5DqVyXU4aFv2eHUs2YwK3XY-RS9HdjkIRJK3E20n251Rw'
      VAPID_PRIVATE_KEY: 'LzjNvVH109jxcAGDMe59zLM-gNaeo9QypJl82Thtmts'
    ports:
     - "8011:8079"

  base:
    image: aeternitybot/aepp-base:develop
    platform: linux/x86_64
    environment:
      VUE_APP_NETWORK_NAME: Devnet (local)
      VUE_APP_NODE_URL: http://localhost:3013
      VUE_APP_MIDDLEWARE_URL: http://localhost:4000
      VUE_APP_EXPLORER_URL: http://localhost:8020
      VUE_APP_COMPILER_URL: http://localhost:8040
      VUE_APP_BACKEND_URL: http://localhost:8011
    ports:
     - "8010:80"
    depends_on:
      base_backend:
        condition: service_started
      mdw:
        condition: service_healthy

  static:
    image: nginx:1.13.8
    ports:
        - 8000:80
    volumes:
        - ${PWD}/nginx/html/devnet:/usr/share/nginx/html
    healthcheck:
        test: ["CMD", "service", "nginx", "status"]
        start_period: 3s
        interval: 3s
        timeout: 1s
        retries: 5
    depends_on:
      mdw:
        condition: service_healthy
      base:
        condition: service_started
      faucet:
        condition: service_started
      aescan:
        condition: service_started

  instructions:
    image: alpine
    command: echo "!!!OPEN http://localhost:8000 FOR MORE INFROMATION ABOUT DEVNET!!!"
    depends_on:
      static:
        condition: service_healthy

volumes:
  ae_node_db:
  ae_mdw_node_db:
  ae_mdw_db:
