version: '3.2'
services:
  hc_mdw:
    platform: linux/x86_64
    # image: aeternity/ae_mdw:1.41.3
    image: aeternity/ae_mdw:local-hc
    build:
      # context: https://github.com/aeternity/ae_mdw.git
      context: ../ae_mdw
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
        NODE_URL: https://releases.aeternity.io/aeternity-v6.8.1-ubuntu-x86_64.tar.gz
        PORT: 24000
        WS_PORT: 24001
    hostname: hc_mdw
    networks:
      default:
        aliases:
          - "hc-mdw.aeternity.localhost"
    ports:
      - "24000:24000" #MDW's default port
      - "24001:24001" #MDW's websocket default port
      - "23113:23113" #Node's default internal API port
      - "23013:23013" #Node's default external API port
      - "23014:23014" #Node's channels default websocket port
    volumes:
      - ${PWD}/node/hyperchain/aeternity.json:/home/aeternity/aeternity.json
      - ${PWD}/node/hyperchain/accounts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.iris/hc_devnet_accounts.json
      - ${PWD}/node/hyperchain/contracts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.iris/hc_devnet_contracts.json
      - ae_hyperchain_node_db:/home/aeternity/node/local/rel/aeternity/data/mnesia
      - ae_hyperchain_mdw_db:/home/aeternity/node/local/rel/aeternity/data/mdw.db
    environment:
      # workaround
      TELEMETRY_STATSD_HOST: localhost
      AETERNITY_CONFIG: /home/aeternity/aeternity.json
      NETWORK_ID: hc_devnet
      PORT: 24000
      WS_PORT: 24001
      AE__HTTP__EXTERNAL__PORT: 23013
      AE__HTTP__INTERNAL__PORT: 23113
      AE__WEBSOCKET__CHANNEL__PORT: 23014
      AE__HTTP__CORS__ALLOW_DOMAINS: '["*"]'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:24000/status"]
        start_period: 20s
        interval: 3s
        timeout: 10s
        retries: 5
    depends_on:
      mdw:
        condition: service_healthy

  hc_faucet:
    platform: linux/x86_64
    image: aeternity/aepp-faucet-nodejs
    environment:
      NODE_URL: http://hc_mdw:23013/
      EPOCH_URL_DEBUG: http://hc_mdw:23113/
      EXPLORER_URL: http://localhost:28020
      FAUCET_ACCOUNT_PRIV_KEY: EE796C442F410F8B1AACFA877A3FE734BC79CE90C8272570AC1DD8CDAC38F104D9CA6CADC0630D0A817C4756E87994B1F3FEA058AECC16720F2A33474B138710
    ports:
     - "28030:5000"
    depends_on:
      hc_mdw:
        condition: service_healthy

  hc_explorer:
    image: aeternity/mdw-frontend
    ports:
     - "28020:3000"
    environment:
      NUXT_APP_NODE_URL: http://hc-mdw.aeternity.localhost:23013/v3
      NUXT_APP_MDW_URL: http://hc-mdw.aeternity.localhost:24000
      NUXT_APP_NODE_WS: ws://localhost:24001/websocket

      NUXT_APP_OTHER_DEPLOYMENTS: ""
      NUXT_APP_NETWORK_NAME: HYPERCHAIN LOCAL
      NUXT_APP_ENABLE_FAUCET: ""
      NUXT_APP_FAUCET_API: http://localhost:28030/account
    depends_on:
      hc_mdw:
        condition: service_healthy

  hc_base_backend:
    image: aeternity/aepp-base-backend:local-hc
    build:
      context: https://github.com/aeternity/aepp-base-remote-connection-backend.git
    environment:
      VAPID_SUBJECT: 'mailto: <info@aeternity.com>'
      VAPID_PUBLIC_KEY: 'BKdMuWCMzVPLTY-ClCNBanQ5Thgji_VMOQKsmTGlTs5DqVyXU4aFv2eHUs2YwK3XY-RS9HdjkIRJK3E20n251Rw'
      VAPID_PRIVATE_KEY: 'LzjNvVH109jxcAGDMe59zLM-gNaeo9QypJl82Thtmts'
    ports:
     - "28011:8079"

  hc_base:
    image: aeternity/aepp-base:local-hc
    build:
      context: https://github.com/aeternity/aepp-base.git#develop
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
        VUE_APP_NETWORK_NAME: Hyperchain Local
        VUE_APP_NODE_URL: http://localhost:23013
        VUE_APP_MDW_URL: http://localhost:24000
        VUE_APP_EXPLORER_URL: http://localhost:28020
        VUE_APP_COMPILER_URL: http://localhost:8040
        VUE_APP_REMOTE_CONNECTION_BACKEND_URL: http://localhost:28011
    environment: {}
    ports:
     - "28010:80"
    depends_on:
      hc_base_backend:
        condition: service_started
      hc_mdw:
        condition: service_healthy

  ui:
    platform: linux/x86_64
    image: aeternity/aepp-hc-ui:pr-10
    environment:
      AE_FAUCET_URL: "http://localhost:28030/"
      AE_WALLET_URL: "http://localhost:28010/"
      AE_NODE_URL: "http://hc-mdw.aeternity.localhost:23013/"
      STAKING_CONTRACT: "ct_LRbi65kmLtE7YMkG6mvG5TxAXTsPJDZjAtsPuaXtRyPA7gnfJ"
      HC_ELECTION_CONTRACT: "ct_t7ESuRFvGdYHwM6KJhKbSnFUJQhnB9aCFed1RWR89ShNDgwWA"
    ports:
     - "8000:3000"
    depends_on:
      hc_mdw:
        condition: service_healthy

volumes:
  ae_hyperchain_node_db:
  ae_hyperchain_mdw_db:
