# Small local network of three nodes using the fastest mean15
version: '3'
services:
  node1:
    image: aeternity/aeternity:${IMAGE_TAG-latest}
    hostname: node1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/node1_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
      - node1_db:/home/aeternity/node/data/mnesia

  node2:
    image: aeternity/aeternity:${IMAGE_TAG-latest}
    hostname: node2
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/node2_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/node2:/home/aeternity/node/keys
      - node2_db:/home/aeternity/node/data/mnesia

  node3:
    image: aeternity/aeternity:${IMAGE_TAG-latest}
    hostname: node3
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/node3_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/node3:/home/aeternity/node/keys
      - node3_db:/home/aeternity/node/data/mnesia

  proxy:
    image: nginx:1.13.8
    hostname: proxy
    ports:
     - "3001:3001"
     - "3002:3002"
     - "3003:3003"
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx/cors.conf:/etc/nginx/cors.conf
      - ${PWD}/nginx/ws.conf:/etc/nginx/ws.conf

volumes:
  ae_node1_db:
  ae_node2_db:
  ae_node3_db:
