version: '3.2'
services:
  # hc_node1:
  #   image: aeternity/aeternity:master
  #   hostname: hc_node1
  #   environment:
  #     AETERNITY_CONFIG: /home/aeternity/aeternity.json
  #     AE__HTTP__CORS__ALLOW_DOMAINS: '["*"]'
  #   volumes:
  #     - ${PWD}/node/hyperchain/config.json:/home/aeternity/aeternity.json
  #     - ${PWD}/node/hyperchain/accounts.json:/home/aeternity/node/data/aecore/.iris/hc_devnet_accounts.json
  #     - ${PWD}/node/hyperchain/contracts.json:/home/aeternity/node/data/aecore/.iris/hc_devnet_contracts.json
  #     - ae_hc_node1_db:/home/aeternity/node/data/mnesia
  #   ports:
  #    - "23013:3013"
  #    - "23113:3113"
  #    - "23014:3014"
  #    - "23313:3313"
  #   healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:3013/v2/status"]
  #       start_period: 10s
  #       interval: 3s
  #       timeout: 10s
  #       retries: 5
  #   depends_on:
  #     node1:
  #       condition: service_healthy

  hc_mdw:
    platform: linux/x86_64
    image: aeternity/ae_mdw:1.38.0
    hostname: hc_mdw
    ports:
      - "24000:4000" #MDW's default port
      - "24001:4001" #MDW's websocket default port
      - "23113:3113" #Node's default internal API port
      - "23013:3013" #Node's default external API port
      - "23014:3014" #Node's channels default websocket port
    volumes:
      - ${PWD}/node/hyperchain/config.json:/home/aeternity/aeternity.json
      # - ${PWD}/node/hyperchain/accounts.json:/home/aeternity/node/data/aecore/.iris/devnet_accounts.json
      - ${PWD}/node/hyperchain/accounts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.iris/ae_devnet_accounts.json
      # - ${PWD}/node/hyperchain/contracts.json:/home/aeternity/node/data/aecore/.iris/devnet_contracts.json
      - ${PWD}/node/hyperchain/contracts.json:/home/aeternity/node/local/rel/aeternity/data/aecore/.iris/ae_devnet_contracts.json
      - ae_hyperchain_node_db:/home/aeternity/node/local/rel/aeternity/data/mnesia
      - ae_hyperchain_mdw_db:/home/aeternity/node/local/rel/aeternity/data/mdw.db
    environment:
      # workaround
      TELEMETRY_STATSD_HOST: localhost
      AETERNITY_CONFIG: /home/aeternity/aeternity.json
      NETWORK_ID: ae_devnet
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4000/status"]
        start_period: 20s
        interval: 3s
        timeout: 10s
        retries: 5

  # hc_faucet:
  #   platform: linux/x86_64
  #   image: aeternity/aepp-faucet-nodejs
  #   environment:
  #     NODE_URL: http://mdw:3013/
  #     EPOCH_URL_DEBUG: http://mdw:3113/
  #     EXPLORER_URL: http://localhost:8020
  #     FAUCET_ACCOUNT_PRIV_KEY: EE796C442F410F8B1AACFA877A3FE734BC79CE90C8272570AC1DD8CDAC38F104D9CA6CADC0630D0A817C4756E87994B1F3FEA058AECC16720F2A33474B138710
  #   ports:
  #    - "28030:5000"
  #   depends_on:
  #     mdw:
  #       condition: service_healthy

  # hc_explorer:
  #   image: aeternity/mdw-frontend:local-hc
  #   build:
  #     context: https://github.com/aeternity/mdw-frontend.git
  #     dockerfile: nginx.Dockerfile
  #     args:
  #       NUXT_APP_NODE_URL: http://localhost:13013/v3

  #       NUXT_APP_MDW_URL: http://localhost:4000
  #       NUXT_APP_NODE_WS: ws://localhost:4001/websocket

  #       NUXT_APP_OTHER_DEPLOYMENTS: ""
  #       NUXT_APP_NETWORK_NAME: HYPERCHAIN LOCAL
  #       NUXT_APP_ENABLE_FAUCET: ""
  #       NUXT_APP_FAUCET_API: http://localhost:8030/account
  #   ports:
  #    - "28020:80"

  # hc_base-backend:
  #   image: aeternity/aepp-base-backend:local-hc
  #   build:
  #     context: https://github.com/aeternity/aepp-base-remote-connection-backend.git
  #   environment:
  #     VAPID_SUBJECT: 'mailto: <info@aeternity.com>'
  #     VAPID_PUBLIC_KEY: 'BKdMuWCMzVPLTY-ClCNBanQ5Thgji_VMOQKsmTGlTs5DqVyXU4aFv2eHUs2YwK3XY-RS9HdjkIRJK3E20n251Rw'
  #     VAPID_PRIVATE_KEY: 'LzjNvVH109jxcAGDMe59zLM-gNaeo9QypJl82Thtmts'
  #   ports:
  #    - "28021:8079"

  # hc_base:
  #   image: aeternity/aepp-base:local-hc
  #   build:
  #     context: https://github.com/aeternity/aepp-base.git#custom_network_build
  #     # context: ../aepp-base
  #     args:
  #       BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
  #       VUE_APP_NETWORK_NAME: Hyperchain Local
  #       VUE_APP_NODE_URL: http://localhost:13013
  #       VUE_APP_MDW_URL: https://mainnet.aeternity.io/mdw
  #       VUE_APP_EXPLORER_URL: https://explorer.aeternity.io
  #       VUE_APP_COMPILER_URL: https://v6.compiler.aepps.com
  #       VUE_APP_REMOTE_CONNECTION_BACKEND_URL: http://localhost:8021
  #   environment: {}
  #   ports:
  #    - "28010:80"

  # ui:
  #   platform: linux/x86_64
  #   image: aeternity/aepp-hc-ui:pr-10
  #   environment:
  #     AE_FAUCET_URL: "http://localhost:8030/"
  #     AE_WALLET_URL: "http://localhost:8010/"
  #     AE_NODE_URL: "http://mdw:3013/"
  #     STAKING_CONTRACT: "ct_LRbi65kmLtE7YMkG6mvG5TxAXTsPJDZjAtsPuaXtRyPA7gnfJ"
  #     HC_ELECTION_CONTRACT: "ct_t7ESuRFvGdYHwM6KJhKbSnFUJQhnB9aCFed1RWR89ShNDgwWA"
  #   ports:
  #    - "8000:3000"
  #   depends_on:
  #     mdw:
  #       condition: service_healthy

volumes:
  ae_hc_node1_db:
  ae_hyperchain_node_db:
  ae_hyperchain_mdw_db:
