# docker run:
#   docker run -p 3013:3013 -p 3014:3014 aeternity/aeternity bin/aeternity foreground -network_id ae_devnet

version: '3'
services:
  node:
    container_name: aeternity_singlenode
    image: aeternity/aeternity:${IMAGE_TAG:-latest}
    hostname: ae_singlenode
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/singlenode_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
      - ae_db:/home/aeternity/node/data/mnesia
    ports:
     - "3013:3013"
     - "3113:3113"
     - "3014:3014"

volumes:
  ae_db:
