version: 2.1
commands:
  run_test_nodes:
    description: Run docker-compose nodes
    steps:
      - run:
          name: Prepare ubuntu user (1000:1000) to run docker commands
          command: |
            sudo usermod -aG docker ubuntu
      - run:
          name: Run docker-compose in background
          command:
            sudo -u ubuntu -E -H docker-compose up
          background: true
      - run:
          name: Give it some time to boot the nodes
          command: sleep 30

  health_check_node:
    description: Health Check a Node
    parameters:
      port:
        type: integer
        default: 3013
    steps:
      - run:
          name: Test external & internal API
          command: |
            EXTERNAL_ADDRESS=localhost:<< parameters.port >> \
            INTERNAL_ADDRESS=localhost:<< parameters.port >> \
            ./test/healthcheck.sh
      - run:
          name: Test external & legacy internal API
          command: |
            EXTERNAL_ADDRESS=localhost:<< parameters.port >> \
            INTERNAL_ADDRESS=localhost:<< parameters.port >>/internal \
            ./test/healthcheck.sh

  integration_tests:
    description: Integration Tests
    steps:
      - health_check_node:
          port: 3001
      - health_check_node:
          port: 3002
      - health_check_node:
          port: 3003

jobs:
  integration_tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run_test_nodes
      - integration_tests

workflows:
  test:
    jobs:
      - integration_tests:
          requires: []
