version: 2.1
commands:
  run_test_nodes:
    description: Run docker-compose nodes
    parameters:
      config:
        type: string
        default: docker-compose.yml
    steps:
      - run:
          name: Run nodes in background
          command: docker-compose -f << parameters.config >> up
          background: true
      - run:
          name: Give it some time to boot the nodes
          command: sleep 30

  health_check_node:
    description: Health Check a Node
    parameters:
      port:
        type: integer
        default: 3013
    steps:
      - run:
          name: Health check APIs
          command: |
            EXTERNAL_ADDR=localhost:<< parameters.port >> \
            INTERNAL_ADDR=localhost:<< parameters.port >> \
            WEBSOCKET_ADDR=localhost:<< parameters.port >> \
            ./test/healthcheck.sh
      - run:
          name: Health check APIs (legacy routing)
          command: |
            EXTERNAL_ADDR=localhost:<< parameters.port >> \
            INTERNAL_ADDR=localhost:<< parameters.port >>/internal \
            WEBSOCKET_ADDR=localhost:<< parameters.port >> \
            ./test/healthcheck.sh

  integration_tests:
    description: Integration Tests
    steps:
      - health_check_node:
          port: 3001
      - health_check_node:
          port: 3002
      - health_check_node:
          port: 3003

jobs:
  integration_tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run_test_nodes
      - integration_tests

  integration_singlenode_tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run_test_nodes:
          config: singlenode.yml
      - run:
          name: singlenode healthcheck API
          command: MIN_PEERS=0 ./test/healthcheck.sh

workflows:
  test:
    jobs:
      - integration_tests:
          requires: []
      - integration_singlenode_tests:
          requires: []
