---
http:
    external:
        port: 3013
    internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true
    cors:
        allow_domains: [""]

websocket:
    channel:
        port: 3014
        listen_address: 0.0.0.0

chain:
    persist: true

mining:
    beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"

system:
    dev_mode: true
    plugins:
        -
          name: aeplugin_dev_mode
